trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'Image-ACR-Appservice'
  imageName: 'mynodeapp'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: build
    repository: $(imageName)
    Dockerfile: 'mynodeapp/Dockerfile'
    buildContext: '$(Build.SourcesDirectory)/mynodeapp'
    tags: |
      $(Build.BuildId)

- task: Docker@2
  displayName: 'Push Docker image to ACR'
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      $(Build.BuildId)
    containerRegistry: $(dockerRegistryServiceConnection)
