trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'Image-ACR-Appservice'
  imageName: 'mynodeapp'
  azureSubscription: 'Image-ACRpush-deploytoAppservice' # Add your Azure subscription service connection name
  appServiceName: 'Azurewebappsuma' # Add your App Service name

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: 'mynodeapp/Dockerfile'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(Build.BuildId)

- task: AzureWebAppContainer@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appServiceName)
    imageName: 'azureappservice.azurecr.io/$(imageName):$(Build.BuildId)'
    dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
    containerCommand: ''
