trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'Image-ACR-Appservice'
  imageName: 'mynodeapp'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: 'mynodeapp/Dockerfile'
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      $(Build.BuildId)
